"""Added is_submitted col in code_assignments

Revision ID: 5007fd6340e6
Revises: 7713226799c6
Create Date: 2025-07-24 20:56:18.618732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5007fd6340e6'
down_revision: Union[str, None] = '7713226799c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable initially
    op.add_column('code_assignments', sa.Column(
        'is_submitted', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE code_assignments SET is_submitted = FALSE")
    # Alter the column to make it non-nullable
    op.alter_column('code_assignments', 'is_submitted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_assignments', 'is_submitted')
    # ### end Alembic commands ###
