"""Add project_id to CodeAssignment

Revision ID: e23907c10c45
Revises: eb254f9628be
Create Date: 2025-07-24 10:41:50.812540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23907c10c45'
down_revision: Union[str, None] = 'eb254f9628be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_assignments', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'code_assignments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_assignments', type_='foreignkey')
    op.drop_column('code_assignments', 'project_id')
    # ### end Alembic commands ###
